const NO_OF_RECORDS = 200;

const breeders = [
  { name: "Stadnina Jan Kowalski", country_iso_code: "PL" },
  { name: "Equus Polska", country_iso_code: "PL" },
  { name: "Stajnia Mazury", country_iso_code: "PL" },
  { name: "Hodowla Podlasie", country_iso_code: "PL" },
  { name: "Krakow Konie", country_iso_code: "PL" },
  { name: "Hodowla Warszawa", country_iso_code: "PL" },
  { name: "Stajnia Gdansk", country_iso_code: "PL" },
  { name: "Hodowla Poznan", country_iso_code: "PL" },
  { name: "Hodowla Wroclaw", country_iso_code: "PL" },
  { name: "Stajnia Lodz", country_iso_code: "PL" },
  { name: "Hodowla Muller", country_iso_code: "DE" },
  { name: "Stadnina Schwarzwald", country_iso_code: "DE" },
  { name: "Bawarskie Konie", country_iso_code: "DE" },
  { name: "Stadnina Saksonia", country_iso_code: "DE" },
  { name: "Stajnia Fontaine", country_iso_code: "FR" },
  { name: "Stajnia Normandia", country_iso_code: "FR" },
  { name: "Stajnia Prowansja", country_iso_code: "FR" },
  { name: "Stajnia Bordeaux", country_iso_code: "FR" },
  { name: "Stajnia Lyon", country_iso_code: "FR" },
  { name: "Centrum Jezdzieckie Rzym", country_iso_code: "IT" },
  { name: "Stajnia Toskania", country_iso_code: "IT" },
  { name: "Konie Veneto", country_iso_code: "IT" },
  { name: "Stajnia Mediolan", country_iso_code: "IT" },
  { name: "Konie Florencja", country_iso_code: "IT" },
  { name: "Farma Koni Kentucky", country_iso_code: "US" },
  { name: "Blekitna Trawa Konie", country_iso_code: "US" },
  { name: "Ranczo Teksas", country_iso_code: "US" },
  { name: "Ranczo Montana", country_iso_code: "US" },
  { name: "Ranczo Floryda", country_iso_code: "US" },
  { name: "Stadnina Zielone Laki", country_iso_code: "GB" },
  { name: "Stadnina Wierzbowy Potok", country_iso_code: "GB" },
  { name: "Stajnia Cotswold", country_iso_code: "GB" },
  { name: "Stajnia Yorkshire", country_iso_code: "GB" },
  { name: "Stajnia Devon", country_iso_code: "GB" },
  { name: "Konie Andaluzyjskie", country_iso_code: "ES" },
  { name: "Yeguada Sierra", country_iso_code: "ES" },
  { name: "Yeguada Katalonska", country_iso_code: "ES" },
  { name: "Yeguada Madryt", country_iso_code: "ES" },
  { name: "Yeguada Sewilla", country_iso_code: "ES" },
  { name: "Lusitano Lusitania", country_iso_code: "PT" },
  { name: "Stadnina Porto", country_iso_code: "PT" },
  { name: "Stadnina Lizbona", country_iso_code: "PT" },
  { name: "Stadnina Faro", country_iso_code: "PT" },
  { name: "Stadnina Coimbra", country_iso_code: "PT" },
  { name: "Stadnina Krolewska Holenderska", country_iso_code: "NL" },
  { name: "Holenderskie Konie", country_iso_code: "NL" },
  { name: "Konie Amsterdam", country_iso_code: "NL" },
  { name: "Konie Rotterdam", country_iso_code: "NL" },
  { name: "Konie Utrecht", country_iso_code: "NL" },
  { name: "Belgijskie Centrum Goracokrwistych", country_iso_code: "BE" },
  { name: "Hodowla Flandryjska", country_iso_code: "BE" },
  { name: "Hodowla Bruksela", country_iso_code: "BE" },
  { name: "Stajnia Antwerpia", country_iso_code: "BE" },
  { name: "Hodowla Gandawa", country_iso_code: "BE" },
  { name: "Szwedzkie Konie", country_iso_code: "SE" },
  { name: "Stajnia Sztokholm", country_iso_code: "SE" },
  { name: "Konie Uppsala", country_iso_code: "SE" },
  { name: "Konie Goteborg", country_iso_code: "SE" },
  { name: "Konie Malmo", country_iso_code: "SE" },
  { name: "Hodowla Fjord", country_iso_code: "NO" },
  { name: "Nordycka Farma Fjord", country_iso_code: "NO" },
  { name: "Farma Fjord Oslo", country_iso_code: "NO" },
  { name: "Fjord Bergen", country_iso_code: "NO" },
  { name: "Fjord Trondheim", country_iso_code: "NO" },
  { name: "Arktyczni Jezdzcy", country_iso_code: "FI" },
  { name: "Stadnina Helsinska", country_iso_code: "FI" },
  { name: "Konie Aurora", country_iso_code: "FI" },
  { name: "Konie Tampere", country_iso_code: "FI" },
  { name: "Konie Oulu", country_iso_code: "FI" },
  { name: "Stajnia Syberyjska", country_iso_code: "RU" },
  { name: "Farma Koni Moskwa", country_iso_code: "RU" },
  { name: "Hodowla Wolga", country_iso_code: "RU" },
  { name: "Konie Ural", country_iso_code: "RU" },
  { name: "Czeski Hrebcin", country_iso_code: "CZ" },
  { name: "Stadnina Morawska", country_iso_code: "CZ" },
  { name: "Hrebcin Praga", country_iso_code: "CZ" },
  { name: "Hrebcin Brno", country_iso_code: "CZ" },
  { name: "Hrebcin Olomouc", country_iso_code: "CZ" },
  { name: "Slowacka Farma", country_iso_code: "SK" },
  { name: "Konie Tatrzanskie", country_iso_code: "SK" },
  { name: "Farma Bratyslawa", country_iso_code: "SK" },
  { name: "Farma Koszyce", country_iso_code: "SK" },
  { name: "Farma Zilina", country_iso_code: "SK" },
  { name: "Stadnina Pannon", country_iso_code: "HU" },
  { name: "Jezdziectwo Dunajskie", country_iso_code: "HU" },
  { name: "Stadnina Budapeszt", country_iso_code: "HU" },
  { name: "Stadnina Szeged", country_iso_code: "HU" },
  { name: "Stadnina Debreczyn", country_iso_code: "HU" },
  { name: "Stadnina Lipica", country_iso_code: "SI" },
  { name: "Konie Balkanu", country_iso_code: "SI" },
  { name: "Stadnina Lublana", country_iso_code: "SI" },
  { name: "Stadnina Split", country_iso_code: "SI" },
  { name: "Stadnina Maribor", country_iso_code: "SI" },
  { name: "Konie Dalmacji", country_iso_code: "HR" },
  { name: "Stadnina Adriatycka", country_iso_code: "HR" },
  { name: "Konie Zagrzeb", country_iso_code: "HR" },
  { name: "Konie Dubrownik", country_iso_code: "HR" },
  { name: "Konie Rijeka", country_iso_code: "HR" },
  { name: "Konie Rumunskie", country_iso_code: "RO" },
  { name: "Farma Transylwanska", country_iso_code: "RO" },
  { name: "Konie Bukareszt", country_iso_code: "RO" },
  { name: "Konie Cluj", country_iso_code: "RO" },
  { name: "Konie Timisoara", country_iso_code: "RO" },
  { name: "Tyrolskie Konie", country_iso_code: "AT" },
  { name: "Alpejskie Konie", country_iso_code: "AT" },
  { name: "Konie Wiedenskie", country_iso_code: "AT" },
  { name: "Konie Salzburg", country_iso_code: "AT" },
  { name: "Konie Innsbruck", country_iso_code: "AT" },
  { name: "Alpejskie Konie", country_iso_code: "CH" },
  { name: "Stadnina Dolina Szwajcarska", country_iso_code: "CH" },
  { name: "Stajnia Zurych", country_iso_code: "CH" },
  { name: "Farma Genewa", country_iso_code: "CH" },
  { name: "Farma Berno", country_iso_code: "CH" },
  { name: "Hodowla O'Connell", country_iso_code: "IE" },
  { name: "Farma Koni Murphy", country_iso_code: "IE" },
  { name: "Konie Galway", country_iso_code: "IE" },
  { name: "Hodowla Cork", country_iso_code: "IE" },
  { name: "Konie Limerick", country_iso_code: "IE" },
  { name: "Poludniowy Krzyz Hodowla", country_iso_code: "AU" },
  { name: "Hodowla Outback", country_iso_code: "AU" },
  { name: "Hodowla Sydney", country_iso_code: "AU" },
  { name: "Hodowla Perth", country_iso_code: "AU" },
  { name: "Hodowla Melbourne", country_iso_code: "AU" },
  { name: "Centrum Koni Kiwi", country_iso_code: "NZ" },
  { name: "Konie Auckland", country_iso_code: "NZ" },
  { name: "Stadnina Wellington", country_iso_code: "NZ" },
  { name: "Konie Christchurch", country_iso_code: "NZ" },
  { name: "Konie Dunedin", country_iso_code: "NZ" },
  { name: "Hodowla Przyladkowa", country_iso_code: "ZA" },
  { name: "Stajnia Sawanna", country_iso_code: "ZA" },
  { name: "Konie Kalahari", country_iso_code: "ZA" },
  { name: "Stajnia Highveld", country_iso_code: "ZA" },
  { name: "Stajnia Drakensberg", country_iso_code: "ZA" },
  { name: "Farma El Caballo", country_iso_code: "AR" },
  { name: "Konie Pampa", country_iso_code: "AR" },
  { name: "Farma Patagonia", country_iso_code: "AR" },
  { name: "Konie Cordoba", country_iso_code: "AR" },
  { name: "Konie Mendoza", country_iso_code: "AR" },
  { name: "Konie Poludniowe", country_iso_code: "BR" },
  { name: "Hodowla Gaucho", country_iso_code: "BR" },
  { name: "Konie Amazonas", country_iso_code: "BR" },
  { name: "Konie Pantanal", country_iso_code: "BR" },
  { name: "Konie Cerrado", country_iso_code: "BR" },
  { name: "Rancho Estrella", country_iso_code: "MX" },
  { name: "Hacienda del Sol", country_iso_code: "MX" },
  { name: "Ranczo Sierra Madre", country_iso_code: "MX" },
  { name: "Ranczo Yucatan", country_iso_code: "MX" },
  { name: "Ranczo Guadalajara", country_iso_code: "MX" },
  { name: "Stadnina Dolina Klonowa", country_iso_code: "CA" },
  { name: "Wietrzna Preria Farma", country_iso_code: "CA" },
  { name: "Konie Ontario", country_iso_code: "CA" },
  { name: "Stadnina Alberta", country_iso_code: "CA" },
  { name: "Stadnina Quebec", country_iso_code: "CA" },
  { name: "Nordyckie Konie", country_iso_code: "DK" },
  { name: "Dunskie Elitarne Konie", country_iso_code: "DK" },
  { name: "Stadnina Kopenhaga", country_iso_code: "DK" },
  { name: "Konie Aarhus", country_iso_code: "DK" },
  { name: "Stadnina Odense", country_iso_code: "DK" },
  { name: "Jezdziectwo Ateny", country_iso_code: "GR" },
  { name: "Konie Saloniki", country_iso_code: "GR" },
  { name: "Stajnia Kreta", country_iso_code: "GR" },
  { name: "Farma Koni Stambul", country_iso_code: "TR" },
  { name: "Stadnina Ankara", country_iso_code: "TR" },
  { name: "Hodowla Izmir", country_iso_code: "TR" },
  { name: "Konie Antalya", country_iso_code: "TR" }
];

exports.seed = async (knex) => {
  await knex("breeders").del();
  await knex("breeders").insert(breeders);
};